global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:9091"]

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:9090"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:9092"]

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:9093"]

  - job_name: "cart-service"
    static_configs:
      - targets: ["cart-service:9094"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:9095"]

  - job_name: "promotion-service"
    static_configs:
      - targets: ["promotion-service:9096"]

  - job_name: "review-service"
    static_configs:
      - targets: ["review-service:9097"]

  - job_name: "logistics-service"
    static_configs:
      - targets: ["logistics-service:9098"]

  - job_name: "message-service"
    static_configs:
      - targets: ["message-service:9099"]

  - job_name: "search-service"
    static_configs:
      - targets: ["search-service:9100"]

  - job_name: "recommend-service"
    static_configs:
      - targets: ["recommend-service:9101"]

  - job_name: "file-service"
    static_configs:
      - targets: ["file-service:9102"]

  - job_name: "job-service"
    static_configs:
      - targets: ["job-service:9103"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:9110"]
