# 服务配置
Name: review-service
ListenOn: 0.0.0.0:8007
Mode: dev

# etcd 服务注册发现
Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: review.rpc

# 超时配置
Timeout: 5000

# CPU 降载阈值
CpuThreshold: 900

# 健康检查
Health: true

# 中间件配置
Middlewares:
  Trace: true
  Recover: true
  Stat: true
  Prometheus: true
  Breaker: true

# 日志配置
Log:
  ServiceName: review-service
  Mode: console
  Level: debug
  Path: logs
  Compress: true
  KeepDays: 7
  StackCooldownMillis: 100

# Prometheus 配置
Prometheus:
  Host: 0.0.0.0
  Port: 9097
  Path: /metrics

# 数据库配置
Database:
  Driver: mysql
  Host: localhost
  Port: 3306
  User: goforge
  Password: "123456"
  Database: go_forge
  Charset: utf8mb4
  MaxOpenConns: 100
  MaxIdleConns: 10
  ConnMaxLifetime: 3600
  ConnMaxIdleTime: 600

# MongoDB配置（用于存储评价详情：图片/视频等）
MongoDB:
  URI: mongodb://root:123456@127.0.0.1:27017/?authSource=admin
  Database: go_forge

